// Image assets from Figma - Downloaded to public/images
export const images = {
  hero1: "/images/hero1.png",
  hero2: "/images/hero2.png",
  whySection: "/images/whySection.png",
  whyPeople: "/images/whyPeople.png",
  vector: "/images/vector.svg",
  camera: "/images/camera.svg",
  wedding: "/images/wedding.svg",
  peopleTeam: "/images/peopleTeam.svg",
  linkMultiple: "/images/linkMultiple.svg",
  arrowRight: "/images/arrowRight.svg",
  arrowRight1: "/images/arrowRight1.svg",
  place: "/images/place.svg",
  place1: "/images/place1.svg",
  vector1: "/images/vector1.svg",
  benefit1: "/images/benefit1.svg",
  benefit2: "/images/benefit2.svg",
  benefit3: "/images/benefit3.svg",
  benefit4: "/images/benefit4.svg",
  benefit5: "/images/benefit5.svg",
  benefit6: "/images/benefit6.svg",
  benefit7: "/images/benefit7.svg",
  benefit8: "/images/benefit8.svg",
  line1: "/images/line1.svg",
  line2: "/images/line2.svg",
  ellipse2: "/images/ellipse2.svg",
  ellipse3: "/images/ellipse3.svg",
  ellipse4: "/images/ellipse4.svg",
  line3: "/images/line3.svg",
  cameraLinear: "/images/cameraLinear.svg",
  rulerLinear: "/images/rulerLinear.svg",
  peopleOutline: "/images/peopleOutline.svg",
  familiarFace: "/images/familiarFace.svg",
  line4: "/images/line4.svg",
  line12: "/images/line12.svg",
  arrowRight2: "/images/arrowRight2.svg",
};
